#include "JamellaD2E.h"
const struct Modifier Modifiers[] =
{
{ 'ar00',"%+d Defense" },
{ 'ar01',"Damage Reduced by %d" },
{ 'ar02',"%+d%% to Defense" },
{ 'ar03',"Magic Damage Reduced by %d" },
{ 'ar04',"Ignores Target's Defense" },
{ 'ar05',"%d to Monster AC per Hit" },
{ 'ar06',"%d%% Target Defense" },
{ 'ar08',"%+d Defense vs Missile" },
{ 'ar09',"%+d Defense vs Melee" },
{ 'at00',"Attacker Takes Damage of %d" },
{ 'at01',"Slight Attack Rate Increase (%d Points)" },
{ 'at02',"Attack Rate Increase (%d Points)" },
{ 'at03',"Greatly Attack Rate Increase (%d Points)" },
{ 'at04',"Attacker Takes Lightning Damage of %d" },
{ 'bl00',"%+d%% Increased Blocking" },
{ 'bl02',"Faster Block Rate" },
{ 'ca00',"Fast Cast Rate" },
{ 'ca01',"Faster Cast Rate" },
{ 'ca02',"Fastest Cast Rate" },
{ 'dc00',"%+d Cold Damage Min" },
{ 'dc01',"%+d Cold Damage Max" },
{ 'dc02',"Half Freeze Duration" },
{ 'dc03',"Cold Duration: %d seconds" },
{ 'df00',"%+d Fire Damage Min" },
{ 'df01',"%+d Fire Damage Max" },
{ 'dl00',"%+d Lightning Damage Min" },
{ 'dl01',"%+d Lightning Damage Max" },
{ 'dm00',"%+d to Maximum Damage" },
{ 'dm01',"%+d to Minimum Damage" },
{ 'dm02',"%+d%% to Damage" },
{ 'dm03',"%d Damage taken Goes to Mana" },
{ 'dp00',"%+d Poison Damage Min" },
{ 'dp01',"%+d Poison Damage Max" },
{ 'dp02',"Poison Length %d seconds" },
{ 'ds00',"%d%% Deadly Strike" },
{ 'dx00',"%+d to Dexterity" },
{ 'gh00',"Fast Hit Recovery" },
{ 'gh01',"Faster Hit Recovery" },
{ 'gh02',"Fastest Hit Recovery" },
{ 'hl08',"Heal Stamina %+d%%" },
{ 'hl10',"Prevent Monster Heal" },
{ 'hl11',"Regenerate Mana %d%%" },
{ 'hl12',"%+d to Max Stamina" },
{ 'hl13',"%d%% Stamina Drain" },
{ 'ht00',"%+d to Attack Rating" },
{ 'ht01',"%d%% Bonus to Attack Rating" },
{ 'hw00',"Hit Causes Monster to Flee" },
{ 'hw01',"Hit blinds target" },
{ 'ib00',"%d%% Extra Gold From Monsters" },
{ 'ib01',"%d%% Better Chance of Getting Magic Item" },
{ 'in00',0 },
{ 'ko00',"Knockback" },
{ 'lf00',"Replenish Life %+d" },
{ 'lt00',"%+d to Light Radius" },
{ 'md01',"%+d%% Damage to Undead" },
{ 'md03',"%+d to Attack Rating against Undead" },
{ 'mh00',"%+d to Life" },
{ 'mh01',"%+d%% to Max Life" },
{ 'mh03',"%d%% Life Stolen Per Hit" },
{ 'mm00',"%+d to Mana" },
{ 'mm01',"%+d%% to Max Mana" },
{ 'mm03',"%d%% Mana Stolen Per Hit" },
{ 'pd00',"Poison Length Reduced by %d%%" },
{ 'ra00',"%+d to each Resistance" },
{ 'ra01',"%d%% To Maximum of each Resistance" },
{ 'rc00',"Cold Resist %d%%" },
{ 'rc01',"%d%% To Maximum Cold Resist" },
{ 'rf00',"Fire Resist %d%%" },
{ 'rf01',"%d%% To Maximum Fire Resist" },
{ 'rl00',"Lightning Resist %d%%" },
{ 'rl01',"%d%% To Maximum Lightning Resist" },
{ 'rp00',"Poison Resist %d%%" },
{ 'rp01',"%d%% To Maximum Poison Resist" },
{ 'rq00',"Requirements %d%%" },
{ 'sk00',"%+d to Amazon Skill Levels" },
{ 'sk01',"%+d to Paladin Skill Levels" },
{ 'sk02',"%+d to Necromancer Skill Levels" },
{ 'sk03',"%+d to Sorceress Skill Levels" },
{ 'sk04',"%+d to Barbarian Skill Levels" },
{ 'sk05',0 },
{ 'sk07',"%+d To Fire Skills" },
{ 'sk08',"%+d To All Skills" },
{ 'sp01',"Freezes Target" },
{ 'sp02',"%d%% Chance of Open Wounds" },
{ 'sp03',"%d%% Chance of Crushing Blow" },
{ 'sp04',0 },
{ 'sp05',"%+d Points of Mana After Each Kill" },
{ 'sp06',0 },
{ 'sp07',"Slows Target By %d%%" },
{ 'sp10',"Cannot Be Frozen" },
{ 'sp13',"Piercing Attack" },
{ 'sp14',"Fires Magic Arrows" },
{ 'sp15',"Fires Explosive Arrows" },
{ 'st00',"%+d to Strength" },
{ 've00',"Fast Run/Walk" },
{ 've01',"Faster Run/Walk" },
{ 've02',"Fastest Run/Walk" },
};
int nModifiers = sizeof Modifiers / sizeof Modifiers[0];
char CodeStringTemp[5];